# Generated by Django 2.1.5 on 2019-01-28 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles_api', '0002_auto_20190128_2329'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofiles',
            old_name='is_stuff',
            new_name='is_staff',
        ),
        migrations.AlterField(
            model_name='userprofiles',
            name='is_superuser',
            field=models.BooleanField(default=False),
        ),
    ]
