# Generated by Django 2.1.5 on 2019-01-28 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles_api', '0003_auto_20190128_2335'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofiles',
            name='is_superuser',
            field=models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status'),
        ),
    ]
