# Generated by Django 2.1.5 on 2019-02-04 20:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles_api', '0005_profilefeeditem'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profilefeeditem',
            old_name='ceated_on',
            new_name='created_on',
        ),
    ]
